import nextConfig from 'eslint-config-next'

const eslintConfig = [
  // Global ignores (applies to all subsequent configs)
  {
    ignores: [
      '.next/**',
      'out/**',
      'dist/**',
      'build/**',
      'node_modules/**',
      '.vercel/**',
      '.turbo/**',
      'coverage/**',
      '*.config.js',
      '*.config.mjs',
      'next-env.d.ts', // Generated by Next.js
      'public/**',
      'pnpm-lock.yaml',
      'package-lock.json',
      'yarn.lock',
    ],
  },
  ...(Array.isArray(nextConfig) ? nextConfig : [nextConfig]),
  {
    rules: {
      // Next.js and React best practices
      'react/react-in-jsx-scope': 'off', // Not needed in Next.js
      'react/prop-types': 'off', // Using TypeScript

      // TypeScript best practices
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',

      // General best practices
      'no-console': 'warn',
      'no-debugger': 'error',
      'prefer-const': 'error',
      'no-var': 'error',

      // Import organization (basic)
      'import/no-anonymous-default-export': 'warn',
    },
  },
]

export default eslintConfig
